### ISSUE TITLE
你好,两个问题

### ISSUE THREAD

**Issue by smallevil** [zsy78191/DeviceAccessViewController#1]
这个东西用着挺方便的.
不过有两点不知道可不可以改一下
1.push出来时,最下边的"设置"有点太靠下,有点挡着了.
2.能不能全点?比如加上拍照/麦克风这些.

谢谢.

**Comment by zsy78191** [comment]
谢谢支持，
1. 当前版本我好像还没有加autolayout， 所有界面布局都是在xib文件中可以随意调整，不会影响功能。
2. 这个我有考虑，拍照和系统照片是同一个。麦克风、通讯录之类的授权我会考虑添加，并且提供可选项。
